[tool.poetry]
name = "banana_crawler"
version = "0.1.0"
description = "A web crawler to language learning"
authors = ["Robson Zagre Junior", "Wesly Carmesini Ataide"]

[tool.poetry.dependencies]
python=">=3.6"
Scrapy="^2.5.1"
genanki="^0.13.0"

